export type ServiceCategory =
  | "licence"
  | "registration"
  | "certificate"
  | "digital-tender"
  | "other";

export interface Service {
  slug: string;
  name: string;
  shortName: string;
  category: ServiceCategory;
  tagline: string;
  description: string;
  whoNeeds: string;
  documents: string[];
  timeline: string;
  popular?: boolean;
}

export const categoryLabels: Record<ServiceCategory, string> = {
  licence: "Licences",
  registration: "Registrations",
  certificate: "Certificates",
  "digital-tender": "Digital & Tender",
  other: "Others",
};

const mk = (
  slug: string,
  name: string,
  category: ServiceCategory,
  tagline: string,
  description: string,
  whoNeeds: string,
  timeline = "3–7 working days",
  popular = false,
): Service => ({
  slug,
  name,
  shortName: name,
  category,
  tagline,
  description,
  whoNeeds,
  documents: [
    "Aadhaar Card",
    "PAN Card",
    "Business address proof",
    "Passport-size photograph",
    "Supporting documents as applicable",
  ],
  timeline,
  popular,
});

export const services: Service[] = [
  // Licences
  mk("gumasta-shop-act", "Gumasta / Shop Act License", "licence",
    "Mandatory for every Bhopal business under MP Shops Act",
    "A Gumasta License (Shop Act License) is a legal document required for all shops and establishments operating in Madhya Pradesh under the MP Shops & Establishments Act.",
    "Every shop, store, salon, clinic, office, hotel, restaurant, or commercial establishment in MP.",
    "3–5 working days", true),
  mk("trade-license", "Trade License", "licence",
    "Municipal permission to run your trade legally",
    "Trade License is issued by the municipal corporation authorising you to carry on a particular trade or business at a specific location.",
    "Shops, hotels, restaurants, factories and service providers within municipal limits."),
  mk("food-license-fssai", "Food License (FSSAI)", "licence",
    "Required for any food business — from tiffin to hotel",
    "FSSAI registration/license is mandatory for all food business operators in India — manufacturers, storage, distributors, retailers, restaurants and caterers.",
    "Food manufacturers, restaurants, cloud kitchens, caterers, food traders and importers.",
    "7–15 working days", true),
  mk("drug-license", "Drug License", "licence",
    "For pharmacies, wholesalers and manufacturers",
    "Drug License is issued under the Drugs & Cosmetics Act to sell, stock, distribute or manufacture pharmaceutical drugs and cosmetics.",
    "Pharmacies, medical stores, drug wholesalers, cosmetic manufacturers and hospitals."),
  mk("labour-license", "Labour License", "licence",
    "For contractors employing workers on site",
    "Labour License under the Contract Labour (Regulation and Abolition) Act is required for contractors engaging 20 or more contract workers.",
    "Contractors, builders and companies deploying contract labour."),
  mk("factory-license", "Factory License", "licence",
    "Statutory license under the Factories Act",
    "Factory License is required under the Factories Act, 1948 for any premises employing 10+ workers using power (or 20+ without power) in a manufacturing process.",
    "Manufacturing units, industrial premises and processing facilities.",
    "15–30 working days", true),
  mk("iec-registration", "Import-Export Code (IEC)", "licence",
    "Your 10-digit gateway to international trade",
    "IEC (Import Export Code) issued by DGFT is a 10-digit code mandatory for any business engaged in import or export of goods and services from India.",
    "Importers, exporters, freight forwarders and e-commerce sellers going global."),
  mk("money-lending-license", "Money Lending License (Sahukari Byaj)", "licence",
    "Legal authority to lend money in Madhya Pradesh",
    "Money Lending License is issued under the MP Money Lenders Act to individuals or firms engaged in the business of money lending.",
    "Money lenders and financing individuals operating in Madhya Pradesh."),
  mk("coloniser-license", "Coloniser License", "licence",
    "Mandatory to develop and sell residential colonies",
    "Coloniser License is required in Madhya Pradesh to develop, sell or transfer plots in residential/commercial colonies.",
    "Real estate developers and colonisers in MP."),
  mk("liquor-license", "Liquor License", "licence",
    "Serve or sell liquor legally in MP",
    "Liquor License is required for the sale, serving or storage of alcoholic beverages under the MP Excise Act.",
    "Bars, restaurants, hotels, clubs and liquor retailers."),
  mk("electrical-contractor-license", "Electrical Contractor License", "licence",
    "Undertake electrical installation work legally",
    "Electrical Contractor License is issued by the MP Electrical Inspectorate to undertake electrical installation, repair and maintenance work.",
    "Electrical contractors, wiremen and electrical firms."),
  mk("security-psara-license", "PSARA (Security Agency) License", "licence",
    "Run a private security guard agency legally",
    "PSARA (Private Security Agencies Regulation Act) License is required to establish and run a private security agency.",
    "Security guard agencies and manpower firms."),
  mk("warehouse-license", "Warehouse License", "licence",
    "Operate a legally registered storage facility",
    "Warehouse License is required to operate a bonded or public warehouse for storage of goods.",
    "Warehousing companies, logistics firms and cold-storage operators."),
  mk("wdra-license", "WDRA License", "licence",
    "Warehousing Development & Regulatory Authority registration",
    "WDRA registration allows warehouses to issue Negotiable Warehouse Receipts (NWRs) to depositors.",
    "Agricultural, industrial and commodity warehouses."),
  mk("petroleum-explosives-license", "Petroleum & Explosives License", "licence",
    "For storage and handling of petroleum and explosives",
    "Petroleum & Explosives (PESO) License is required for storage, handling and transport of petroleum products and explosives.",
    "Fuel stations, industrial gas storage facilities and blasting contractors.",
    "30–60 working days"),

  // Registrations
  mk("gst-registration", "GST Registration", "registration",
    "Get your GSTIN in 3–7 working days",
    "GST Registration is mandatory for businesses with annual turnover above ₹20 lakh, or for inter-state trade, e-commerce and import-export.",
    "Businesses with turnover above ₹20L, inter-state sellers, e-commerce sellers, importers/exporters.",
    "3–7 working days", true),
  mk("msme-udyam-registration", "MSME / Udyam Registration", "registration",
    "Unlock MSME benefits in 1–2 days",
    "Udyam Registration is the official government portal for registering Micro, Small and Medium Enterprises, giving access to subsidies, priority lending and tender benefits.",
    "Any Micro, Small or Medium Enterprise across manufacturing or services.",
    "1–2 working days", true),
  mk("startup-india-registration", "Startup India Registration", "registration",
    "DPIIT recognition, tax holidays & funding access",
    "Startup India / DPIIT Recognition unlocks tax exemptions, self-certification, IPR benefits and access to the Startup India Seed Fund.",
    "Innovative startups incorporated as Pvt Ltd, LLP or Partnership less than 10 years old."),
  mk("pwd-cpwd-registration", "PWD / CPWD Registration", "registration",
    "Bid for state and central government works",
    "PWD/CPWD Contractor Registration allows firms to bid for state and central public works tenders.",
    "Civil, electrical and mechanical contractors seeking government work."),
  mk("firm-society-registration", "Firm & Society Registration", "registration",
    "Partnership firms and societies under Indian law",
    "Registration of Partnership Firms and Societies under the Indian Partnership Act and Societies Registration Act.",
    "Partnership businesses and non-profit societies."),
  mk("ngodarpan-registration", "NGO / Darpan Registration", "registration",
    "NGO Darpan ID for CSR & government grants",
    "NGO Darpan Registration provides a unique ID to NGOs and Trusts, mandatory for receiving government grants and CSR funds.",
    "NGOs, Trusts and Section 8 companies."),
  mk("isi-mark-registration", "ISI Mark Registration", "registration",
    "BIS certification for your product quality",
    "ISI Mark (BIS Certification) is a quality mark issued by the Bureau of Indian Standards for products conforming to Indian Standards.",
    "Manufacturers of notified consumer and industrial goods."),
  mk("gem-registration", "GEM Registration", "registration",
    "Sell to central & state government departments",
    "GeM (Government e-Marketplace) Registration allows sellers and service providers to list and sell to all government departments online.",
    "Manufacturers, resellers, service providers of any size.",
    "3–5 working days", true),
  mk("nsic-registration", "NSIC Registration", "registration",
    "Single-point registration for government tenders",
    "NSIC (National Small Industries Corporation) Single Point Registration gives MSMEs preference in government procurement.",
    "MSMEs bidding for central government tenders."),
  mk("esic-registration", "ESIC Registration", "registration",
    "Employee State Insurance for your workforce",
    "ESIC Registration is mandatory for establishments with 10+ employees earning up to ₹21,000/month.",
    "Factories, shops and establishments meeting the ESIC threshold."),
  mk("epfo-registration", "EPFO Registration", "registration",
    "Provident Fund registration for employers",
    "EPFO Registration under the EPF & MP Act is mandatory for establishments employing 20 or more persons.",
    "Employers with 20+ employees."),
  mk("pvt-opc-llp-registration", "Pvt / OPC / LLP Registration", "registration",
    "Incorporate your company the right way",
    "Company Incorporation under the Companies Act — Private Limited, One Person Company, or Limited Liability Partnership.",
    "Founders, professionals and entrepreneurs formalising their venture.",
    "7–14 working days"),
  mk("trademark-registration", "Trademark Registration", "registration",
    "Protect your brand name and logo across India",
    "Trademark Registration under the Trade Marks Act, 1999 gives you exclusive rights to your brand name, logo, slogan or design.",
    "Every business, startup and personal brand."),
  mk("trust-registration", "Trust Registration", "registration",
    "Public or private trust incorporation",
    "Trust Registration under the Indian Trusts Act formalises public charitable or private trusts.",
    "Charitable, religious and family trusts."),
  mk("rera-registration", "RERA Registration", "registration",
    "MP-RERA registration for real estate projects & agents",
    "RERA Registration under the Real Estate (Regulation and Development) Act is mandatory for real estate projects above 500 sqm or 8 units, and for all agents.",
    "Real estate developers, promoters and agents."),
  mk("rehwasi-society-registration", "Rehwasi Society Registration", "registration",
    "Residential welfare society registration in MP",
    "Registration of Rehwasi (Residents Welfare) Society under the MP Societies Registrikaran Adhiniyam.",
    "Residents Welfare Associations in Madhya Pradesh."),
  mk("bocw-registration", "BOCW Act Registration", "registration",
    "Building & Other Construction Workers Welfare",
    "BOCW Registration under the Building and Other Construction Workers Act — for construction employers and workers.",
    "Construction companies and building contractors."),

  // Certificates
  mk("pollution-control-certificate", "Pollution Control Certificate", "certificate",
    "CTE / CTO from MP Pollution Control Board",
    "Consent to Establish (CTE) and Consent to Operate (CTO) issued by the MP Pollution Control Board under Air & Water Acts.",
    "Industries, factories, hotels, hospitals and commercial establishments."),
  mk("iso-certification", "ISO Certification", "certificate",
    "ISO 9001, 14001, 45001 and more",
    "ISO Certification for Quality (9001), Environment (14001), Health & Safety (45001), Information Security (27001) and other international standards.",
    "Any organisation seeking process standardisation and credibility."),
  mk("birth-certificate", "Birth Certificate", "certificate",
    "Municipal birth certificate procurement & corrections",
    "Assistance in obtaining, correcting or getting duplicate birth certificates from the concerned municipal authority.",
    "Individuals and families needing certified birth records."),
  mk("marriage-certificate", "Marriage Certificate", "certificate",
    "Marriage registration under Hindu Marriage / Special Marriage Act",
    "Marriage Registration under the Hindu Marriage Act or Special Marriage Act with certified marriage certificate delivery.",
    "Newly-wed couples and NRIs."),
  mk("income-certificate", "Income Certificate", "certificate",
    "Government-issued income proof for schemes & scholarships",
    "Income Certificate issued by the tehsil/SDM office — required for scholarships, subsidies and government scheme eligibility.",
    "Students, EWS applicants and welfare-scheme beneficiaries."),

  // Digital & Tender
  mk("digital-signature", "Digital Signature (Class 3)", "digital-tender",
    "Class 3 DSC in 24 hours for MCA, GST, e-Tenders",
    "Class 3 Digital Signature Certificate for signing e-tenders, GST, MCA, ITR, EPFO and any government portal filings.",
    "Company directors, GST filers, tender bidders and professionals.",
    "24 hours", true),
  mk("e-tender", "E-Tender Registration & Bidding", "digital-tender",
    "End-to-end e-tendering on NIC & MPTENDERS",
    "Complete e-tender lifecycle — vendor registration, digital signature setup, tender search, bid preparation and online submission on NIC and MPTENDERS portals.",
    "Contractors, suppliers and service providers bidding for government tenders.",
    "Ongoing service", true),
  mk("gem-tender", "GEM Tender Services", "digital-tender",
    "Bid preparation and submission on GEM portal",
    "Expert GEM (Government e-Marketplace) tender services — catalog listing, bid participation, reverse auction support and order fulfilment.",
    "GEM sellers and service providers.",
    "Ongoing service", true),

  // Others
  mk("passport-seva", "Passport Seva", "other",
    "Passport application, renewal and appointment assistance",
    "Passport Seva assistance — fresh application, renewal, re-issue, tatkal, address change and appointment scheduling.",
    "Individuals and families needing passport services."),
  mk("government-loans-project-report", "Government Loans Project Report", "other",
    "PMEGP, Mudra, Stand-Up India project reports",
    "Bankable project reports for PMEGP, Mudra, Stand-Up India, CGTMSE and other government-subsidised loan schemes.",
    "MSMEs, entrepreneurs and start-ups seeking bank finance."),
  mk("fire-cgwa-lift-noc", "Fire / CGWA / Lift NOC", "other",
    "Fire, ground water and lift installation NOCs",
    "No-Objection Certificates from Fire Department, Central Ground Water Authority (CGWA) and Lift Inspectorate.",
    "Commercial buildings, industries and multi-storey developers."),
  mk("labour-welfare-fund", "Labour Welfare Fund (LWF)", "other",
    "Employer LWF registration & compliance",
    "Registration and compliance under the Labour Welfare Fund Act — employer & employee contributions.",
    "Establishments falling under LWF applicability."),
  mk("income-tax-return", "Income Tax Return Filing", "other",
    "ITR filing for individuals, firms & companies",
    "Accurate and timely ITR filing — salaried, business, capital gains, presumptive, company and LLP returns.",
    "Individuals, professionals, businesses and companies."),
];

export const getServiceBySlug = (slug: string): Service | undefined =>
  services.find((s) => s.slug === slug);

export const servicesByCategory = (cat: ServiceCategory): Service[] =>
  services.filter((s) => s.category === cat);
